### ISSUE TITLE
Float parsing blows up on % symbol

### ISSUE THREAD

**Issue by jhmoore** [qbwc/qbxml#18]
One of our customers' Items query is returning a percentage that has an actual `%` symbol in the float field.  E.g.

```
<PricePercent>18.0%</PricePercent>
```

The implementation of [FLOATTYPE](https://github.com/qbwc/qbxml/blob/master/lib/qbxml/types.rb#L8) uses `Float()`, which is throwing an exception for us when trying to parse `18.0%`.  Any reason it couldn't be a `to_f` there instead?

**Comment by JasonBarnabe** [comment]
Only reason I can see would be in case it returns a completely non-float number, you'd want an error instead of 0.0. But I've never had that case, nor have I heard of anyone who has, so a PR for `to_f` would be OK with me.

**Comment by jhmoore** [comment]
Thanks!  Opened https://github.com/qbwc/qbxml/pull/19
