### ISSUE TITLE
Intention to release?

### ISSUE THREAD

**Issue by thomascarli** [qbwc/qbxml#22]
Hey all, I was wondering if there were any plans for a release of the handful of issues that have been fixed since the last release.

**Comment by JasonBarnabe** [comment]
The only reason I'm waiting is to hear if anyone is having any problems with the changes, specifically #17. If you're working off master and it works for you, it would be helpful to for me to know.

**Comment by nicholejeannine** [comment]
I'm using the master branch currently in a real-world project, and can confirm that this change works for top-level elements (e.g., 'customer_ret').  However, , #17 is still an issue for nested elements (e.g., estimate_line_ret within estimate_ret is an Array unless there is only a single line item, in which case it is a Qbxml::Hash). 
I'm still new at writing specs, so it's just my word for now .... I'll try to update this post in the future once I figure out how to relay my observations via some kind of testing framework :)

**Comment by JasonBarnabe** [comment]
0.4.0 has been released.
